@startuml Andexor Grass Spider (AGS) - Get Domain Registration Data - State Diagrams

' SPDX-License-Identifier: Apache-2.0
' Copyright 2026 Andexor Network, Inc.
' Author: Ed Jenkins<ed@andexor.net>

title Andexor Grass Spider (AGS)\nGet Domain Registration Data\nState Diagrams

' Colors defined by Andexor Network Design System

!$ANDEXOR_BLUE_50  = "#F3F7FC"
!$ANDEXOR_BLUE_100 = "#E7EFF8"
!$ANDEXOR_BLUE_200 = "#C5D8EF"
!$ANDEXOR_BLUE_300 = "#8FB6E2"
!$ANDEXOR_BLUE_400 = "#4A8BD0"
!$ANDEXOR_BLUE_500 = "#1A5FA8"

!$OLD_GOLD_300 = "#F8D066"
!$OLD_GOLD_500 = "#EAAA00"

<style>

root {
    BackgroundColor $ANDEXOR_BLUE_200
    HorizontalAlignment center
    LineColor $ANDEXOR_BLUE_400
    LineThickness 4
    Margin 20
    RoundCorner 20
    Shadowing 1
}

title {
    BackgroundColor $ANDEXOR_BLUE_500
    FontColor $ANDEXOR_BLUE_50
    Margin 20
    Padding 20
}

arrow {
    FontColor $ANDEXOR_BLUE_500
    FontStyle bold
}

stateDiagram {

    FontColor $ANDEXOR_BLUE_500
    LineColor $ANDEXOR_BLUE_500

}

</style>

'AGS RDAP Agent
'AGS RDAP Bootstrap Service
'AGS RDAP Authoritative Service

'layers
'REST
  'live data
  'persistant data
'events
  'incoming/queue/consumer
  'outgoing/topic/producer
  'DLQ topic/queue
  'rate limiter / message pump
  'dependency downtime
'telemetry
  'logs
  'merics
  'traces
  'profiles?
  'third-party system dependency uptime monitor
'AI
  'analyzers
    'data
    'metadata
    'DLQ
  'analytics reporter
  'issue alerter
'documentation

'ags_rdap_bootstrap_service_database

'status table
'- id
'- run_id
'- event_ts
'process_status
'  - STARTED
'  - OK
'  - ERROR
'- url

'ags_rdap_authoritative_service_database

'status table
'- id
'- run_id
'- event_ts
'process_status
'  - STARTED
'  - OK
'  - ERROR
'- registration_status
'  - UNKNOWN
'  - NOT_REGISTERED
'  - IS_REGISTERED
'- url

state "Scenario 1\nUnable to get referral" as S1 {
    state "AUDIT_STARTED" as S1_AUDIT_STARTED: The audit has started.
    [*] --> S1_AUDIT_STARTED
    S1_AUDIT_STARTED --> [*]
}

state "Scenario 2\nUnable to get data" as S2 {
    state "AUDIT_STARTED" as S2_AUDIT_STARTED: The audit has started.
    state "UNABLE_TO_GET_DATA" as S2_UNABLE_TO_GET_DATA: Unable to get\nregistration data.
    [*] --> S2_AUDIT_STARTED
    S2_AUDIT_STARTED --> S2_UNABLE_TO_GET_DATA
    S2_UNABLE_TO_GET_DATA --> [*]
}

---

state "Scenario 3\nNot Registered" as S3 {
    state "MAIN_UNEXPLORED" as S2_DOMAIN_UNEXPLORED: The audit has begun.
    state "DOMAIN_NOT_REGISTERED" as S2_DOMAIN_NOT_REGISTERED: The domain is not registered.
    S2_DOMAIN_UNEXPLORED --> S2_DOMAIN_NOT_REGISTERED
    S2_DOMAIN_NOT_REGISTERED --> [*]
}

state "Scenario 3\nIs Registered" as S3 {
    state "DOMAIN_UNEXPLORED" as S3_DOMAIN_UNEXPLORED: The audit has begun.
    state "DOMAIN_REGISTERED" as S3_DOMAIN_REGISTERED: The domain is registered.
    S3_DOMAIN_UNEXPLORED --> S3_DOMAIN_REGISTERED
    S3_DOMAIN_REGISTERED --> [*]
}

' DOMAIN_REGISTERED --> DOMAIN_NOT_REGISTERED
' DOMAIN_NOT_REGISTERED --> DOMAIN_REGISTERED

@enduml
